// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBScOUH8uoz0OjzmeMZpIAegniNU-axDEI',
    appId: '1:515835567480:web:13c5d1a0159cabb645bc8d',
    messagingSenderId: '515835567480',
    projectId: 'unmurce-2f3e3',
    authDomain: 'unmurce-2f3e3.firebaseapp.com',
    storageBucket: 'unmurce-2f3e3.firebasestorage.app',
    measurementId: 'G-H74ZL6M5Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe59AcakNuAd5CfiEqCLK6IOCwB_kfMBs',
    appId: '1:515835567480:android:bae3ea2beb911dfb45bc8d',
    messagingSenderId: '515835567480',
    projectId: 'unmurce-2f3e3',
    storageBucket: 'unmurce-2f3e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwLcGfgq64wmGU4Nj1CIhcFoRUBvDLv3E',
    appId: '1:515835567480:ios:436687636c83e33b45bc8d',
    messagingSenderId: '515835567480',
    projectId: 'unmurce-2f3e3',
    storageBucket: 'unmurce-2f3e3.firebasestorage.app',
    iosBundleId: 'com.example.expenseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwLcGfgq64wmGU4Nj1CIhcFoRUBvDLv3E',
    appId: '1:515835567480:ios:436687636c83e33b45bc8d',
    messagingSenderId: '515835567480',
    projectId: 'unmurce-2f3e3',
    storageBucket: 'unmurce-2f3e3.firebasestorage.app',
    iosBundleId: 'com.example.expenseapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBScOUH8uoz0OjzmeMZpIAegniNU-axDEI',
    appId: '1:515835567480:web:13ad9ae19d71c23345bc8d',
    messagingSenderId: '515835567480',
    projectId: 'unmurce-2f3e3',
    authDomain: 'unmurce-2f3e3.firebaseapp.com',
    storageBucket: 'unmurce-2f3e3.firebasestorage.app',
    measurementId: 'G-XTQT3J85CV',
  );
}
